/* -*- C++ -*- */
/* Generated by /home/zack/github/OpenDDS/bin/opendds_idl version 3.10 (ACE version 6.2a_p11) running on input file T1.idl */
#ifndef OPENDDS_IDL_GENERATED_T1TYPESUPPORTIMPL_H_BVN5SD
#define OPENDDS_IDL_GENERATED_T1TYPESUPPORTIMPL_H_BVN5SD
#include "T1C.h"
#include "dds/DCPS/Definitions.h"
#include "T1TypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: mT1 */



/* Begin STRUCT: T1 */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const mT1::T1& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const mT1::T1& stru);

bool operator>>(Serializer& strm, mT1::T1& stru);

size_t gen_max_marshaled_size(const mT1::T1& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const mT1::T1> stru, bool align);

void gen_find_size(KeyOnly<const mT1::T1> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const mT1::T1> stru);

bool operator>>(Serializer& strm, KeyOnly<mT1::T1> stru);

template <>
struct MarshalTraits<mT1::T1> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace mT1 {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  T1_OpenDDS_KeyLessThan {
  bool operator()(const mT1::T1&, const mT1::T1&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace mT1 {
class T1TypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<mT1::T1> {
  typedef mT1::T1 MessageType;
  typedef mT1::T1Seq MessageSequenceType;
  typedef mT1::T1TypeSupport TypeSupportType;
  typedef mT1::T1TypeSupportImpl TypeSupportTypeImpl;
  typedef mT1::T1DataWriter DataWriterType;
  typedef mT1::T1DataReader DataReaderType;
  typedef mT1::T1_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "mT1::T1"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace mT1 {
class  T1TypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<T1TypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<T1> TraitsType;
  typedef T1TypeSupport TypeSupportType;
  typedef T1TypeSupport::_var_type _var_type;
  typedef T1TypeSupport::_ptr_type _ptr_type;

  T1TypeSupportImpl() {}
  virtual ~T1TypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static T1TypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<mT1::T1>();
void gen_skip_over(Serializer& ser, mT1::T1*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: T1 */

/* End MODULE: mT1 */
#endif /* OPENDDS_IDL_GENERATED_T1TYPESUPPORTIMPL_H_BVN5SD */
