// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p11
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "T1TypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "T1TypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for mT1::T1TypeSupport.

mT1::T1TypeSupport_ptr
TAO::Objref_Traits<mT1::T1TypeSupport>::duplicate (
    mT1::T1TypeSupport_ptr p)
{
  return mT1::T1TypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<mT1::T1TypeSupport>::release (
    mT1::T1TypeSupport_ptr p)
{
  ::CORBA::release (p);
}

mT1::T1TypeSupport_ptr
TAO::Objref_Traits<mT1::T1TypeSupport>::nil (void)
{
  return mT1::T1TypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<mT1::T1TypeSupport>::marshal (
    const mT1::T1TypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

mT1::T1TypeSupport::T1TypeSupport (void)
{}

mT1::T1TypeSupport::~T1TypeSupport (void)
{
}

mT1::T1TypeSupport_ptr
mT1::T1TypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1TypeSupport::_duplicate (
      dynamic_cast<T1TypeSupport_ptr> (_tao_objref)
    );
}

mT1::T1TypeSupport_ptr
mT1::T1TypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1TypeSupport::_duplicate (
      dynamic_cast<T1TypeSupport_ptr> (_tao_objref)
    );
}

mT1::T1TypeSupport_ptr
mT1::T1TypeSupport::_nil (void)
{
  return 0;
}

mT1::T1TypeSupport_ptr
mT1::T1TypeSupport::_duplicate (T1TypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
mT1::T1TypeSupport::_tao_release (T1TypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
mT1::T1TypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:mT1/T1TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* mT1::T1TypeSupport::_interface_repository_id (void) const
{
  return "IDL:mT1/T1TypeSupport:1.0";
}

::CORBA::Boolean
mT1::T1TypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for mT1::T1DataWriter.

mT1::T1DataWriter_ptr
TAO::Objref_Traits<mT1::T1DataWriter>::duplicate (
    mT1::T1DataWriter_ptr p)
{
  return mT1::T1DataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<mT1::T1DataWriter>::release (
    mT1::T1DataWriter_ptr p)
{
  ::CORBA::release (p);
}

mT1::T1DataWriter_ptr
TAO::Objref_Traits<mT1::T1DataWriter>::nil (void)
{
  return mT1::T1DataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<mT1::T1DataWriter>::marshal (
    const mT1::T1DataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

mT1::T1DataWriter::T1DataWriter (void)
{}

mT1::T1DataWriter::~T1DataWriter (void)
{
}

mT1::T1DataWriter_ptr
mT1::T1DataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1DataWriter::_duplicate (
      dynamic_cast<T1DataWriter_ptr> (_tao_objref)
    );
}

mT1::T1DataWriter_ptr
mT1::T1DataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1DataWriter::_duplicate (
      dynamic_cast<T1DataWriter_ptr> (_tao_objref)
    );
}

mT1::T1DataWriter_ptr
mT1::T1DataWriter::_nil (void)
{
  return 0;
}

mT1::T1DataWriter_ptr
mT1::T1DataWriter::_duplicate (T1DataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
mT1::T1DataWriter::_tao_release (T1DataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
mT1::T1DataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:mT1/T1DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* mT1::T1DataWriter::_interface_repository_id (void) const
{
  return "IDL:mT1/T1DataWriter:1.0";
}

::CORBA::Boolean
mT1::T1DataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for mT1::T1DataReader.

mT1::T1DataReader_ptr
TAO::Objref_Traits<mT1::T1DataReader>::duplicate (
    mT1::T1DataReader_ptr p)
{
  return mT1::T1DataReader::_duplicate (p);
}

void
TAO::Objref_Traits<mT1::T1DataReader>::release (
    mT1::T1DataReader_ptr p)
{
  ::CORBA::release (p);
}

mT1::T1DataReader_ptr
TAO::Objref_Traits<mT1::T1DataReader>::nil (void)
{
  return mT1::T1DataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<mT1::T1DataReader>::marshal (
    const mT1::T1DataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

mT1::T1DataReader::T1DataReader (void)
{}

mT1::T1DataReader::~T1DataReader (void)
{
}

mT1::T1DataReader_ptr
mT1::T1DataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1DataReader::_duplicate (
      dynamic_cast<T1DataReader_ptr> (_tao_objref)
    );
}

mT1::T1DataReader_ptr
mT1::T1DataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return T1DataReader::_duplicate (
      dynamic_cast<T1DataReader_ptr> (_tao_objref)
    );
}

mT1::T1DataReader_ptr
mT1::T1DataReader::_nil (void)
{
  return 0;
}

mT1::T1DataReader_ptr
mT1::T1DataReader::_duplicate (T1DataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
mT1::T1DataReader::_tao_release (T1DataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
mT1::T1DataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:mT1/T1DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* mT1::T1DataReader::_interface_repository_id (void) const
{
  return "IDL:mT1/T1DataReader:1.0";
}

::CORBA::Boolean
mT1::T1DataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

