module Messager
{
	#pragma DCPS_DATA_TYPE "Messager::Messages"
	#pragma DCPS_DATA_KEY  "Messager::Messages id"
	typedef struct sMessage1
	{
		string from;
		string subject;
		long subject_id;
		long count;
	} Message1;
	typedef struct sMessage2
	{
		string from;
		string subject;
		long subject_id;
		long count;
	} Message2;
	struct Messages
	{
		long id;
		long stamp;
		Message1 M1;
		Message2 M2;
	};

};

