######################################################################
# Automatically generated by qmake (2.01a) Wed May 31 18:05:34 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += UiAction.h
FORMS += Ui.ui
SOURCES += main.cpp UiAction.cpp
